[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my-project"
version = "0.1.0"
requires-python = ">= 3.10"

[tool.setuptools.packages.find]
where = ["app"]

[tool.pytest.ini_options]